### ISSUE TITLE
Running image as non-root user fails to copy provided conf files like prconfig.xml

### ISSUE THREAD

**Issue by Emilio-Pega** [pegasystems/docker-pega-web-ready#50]
**Describe the bug**
If I provide a volume mapping for the /opt/pega/config dir when I run the image as a non-root user, the entry script fails to copy over the various config files.

**To Reproduce**
1. Create a local directory containing a prconfig.xml file (/var/customconf/prconfig.xml)
2. Run the image as a non-root user mapping the volume `$ docker run -v /var/customconf:/opt/pega/config --user 1000 pega-tomcat:latest`

**Expected behavior**
The mapped files are copied correctly

**Screenshots**
```
2019/12/11 13:50:59 unable to chmod temp file: chmod /usr/local/tomcat/conf/Catalina/localhost/prweb.xml: operation not permitted
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
cp: cannot create regular file '/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prlog4j2.xml': Permission denied
Loading prconfig from /opt/pega/config/prconfig.xml...
cp: cannot create regular file '/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prconfig.xml': Permission denied
Loading context.xml from /opt/pega/config/context.xml...
2019/12/11 13:50:59 unable to chmod temp file: chmod /usr/local/tomcat/conf/tomcat-users.xml: operation not permitted
```

**Comment by Emilio-Pega** [comment]
Adding `RUN chmod -R g+rw ${CATALINA_HOME}/webapps` to theDockerfile resolves the issue

**Comment by Emilio-Pega** [comment]
For all you pega devs this is BUG-528213

**Comment by zitikay** [comment]
This is fixed in the internal pega image, and documented in the README in this repo (merged PR #51 )

**Comment by pawankumardv2901** [comment]
i still see this file permission issue even though i explicitly granted permissions to webapps folder. below is my Dockerfile i used to build a custom image

FROM pega-docker.downloads.pega.com/platform/pega:8.7.1

# Make a jdbc driver available to tomcat applications
COPY --chown=pegauser:root ./jdbcdrivers/postgresql-42.2.14.jar ${CATALINA_HOME}/lib/
COPY --chown=pegauser:root ./jdbcdrivers/db2jcc_license_cu-6.0.0.jar ${CATALINA_HOME}/lib/
COPY --chown=pegauser:root ./jdbcdrivers/db2jcc-6.0.0.jar ${CATALINA_HOME}/lib/
COPY --chown=pegauser:root ./jdbcdrivers/ojdbc8-12.2.0.1.jar ${CATALINA_HOME}/lib/
COPY --chown=pegauser:root ./jdbcdrivers/sqljdbc4-4.0.jar ${CATALINA_HOME}/lib/
RUN chmod g+rw   ${CATALINA_HOME}/lib/postgresql-42.2.14.jar
RUN chmod g+rw   ${CATALINA_HOME}/lib/db2jcc_license_cu-6.0.0.jar
RUN chmod g+rw   ${CATALINA_HOME}/lib/db2jcc-6.0.0.jar
RUN chmod g+rw   ${CATALINA_HOME}/lib/ojdbc8-12.2.0.1.jar
RUN chmod g+rw   ${CATALINA_HOME}/lib/sqljdbc4-4.0.jar

RUN chmod g+rw ${CATALINA_HOME}/webapps/prweb/WEB-INF/classes/prconfig.xml
RUN chmod g+rw ${CATALINA_HOME}/webapps/prweb/WEB-INF/classes/prlog4j2.xml
RUN chmod -R g+rw ${CATALINA_HOME}/webapps
